<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="2.469">
  <testcase classname="__main__.qa_plcp_transmit" name="test_001_t" time="2.4688">
    <failure type="exceptions.AssertionError">nan != -3991.98291015625 within 195424 places
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/roee/Dropbox/Thesis/gr-plc/gr-plc/python/qa_plcp_transmit.py", line 75, in test_001_t
    self.assertFloatTuplesAlmostEqual(expected_result[0:n], result_data[0:n], n)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr_unittest.py", line 90, in assertFloatTuplesAlmostEqual
    self.assertAlmostEqual (a[i], b[i], places, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 561, in assertAlmostEqual
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
